# Менеджер плагинов
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Сохранение сессий
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Автосохранение каждые 15 минут
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Сохранять содержимое pane (опционально)
set -g @resurrect-capture-pane-contents 'on'

set -g mouse on

# Инициализация TPM (эта строка должна быть ПОСЛЕДНЕЙ)
run '~/.tmux/plugins/tpm/tpm'
